DROP TABLE IF EXISTS LIBRARY;
DROP TABLE IF EXISTS BOOK;

CREATE TABLE LIBRARY(  
id INT AUTO_INCREMENT  PRIMARY KEY,  
name VARCHAR(50) NOT NULL,   
description VARCHAR(1000) NULL
); 

CREATE TABLE BOOK(  
id INT AUTO_INCREMENT  PRIMARY KEY, 
name VARCHAR(50) NOT NULL,  
author VARCHAR(50) NULL,  
description VARCHAR(1000) NULL,
lib_id INT references LIBRARY(ID)
);